name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.0.0
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --target thumbv6m-none-eabi --verbose

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/tarpaulin@v0.1
    - uses: codecov/codecov-action@v1
